name: "Deploy to Cloud Run"
author: "SafeHouse Tech."
description: |-
  An action to deploy a docker image to cloud run.
inputs:
  env_vars:
    description: |-
      environment variables to pass to the container.
    required: false
  secrets:
    description: |-
      Secrets required during deployment.
    required: false
  credentials_json:
    description: |-
      Credential file for GCP authentication.
    required: true
  gcloud_args:
    description: |-
      Extra gcloud args for cloud run deployment.
    required: false
  gcp_region:
    description: |-
      The GCP region to deploy to.
    required: true
  shared_project_id:
    description: |-
      Shared project id for shared VPC connection.
    required: false
  project_id:
    description: |-
      GCP project ID to deploy on.
    required: true
  service_id:
    description: |-
      This is the name of service which needs to be deployed.
    required: true
  sql_instance:
    description: |-
      SQL instance name to attach it to cloud run service.
    required: false
  set-cloudsql-instances:
    description: |-
      This is to set cloud sql instance.
    required: false
  port:
    description: |-
      Port number on which application is running.
    default: 3000
  service_account:
    description: |-
      Service acoount to attact to cloud run service.
    required: true
  tag:
    description: |-
      container tag
    default: latest
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Authenticate in GCloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.credentials_json }}
    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ inputs.project_id }}
    - name: Set VPC_CONNECTOR env variable
      shell: bash
      run: |
        if [ ! -z "${{ inputs.shared_project_id }}" ]; then
          # check if a connector with the region-based name exists
          if gcloud compute networks vpc-access connectors describe "${{ inputs.gcp_region }}" --region "${{ inputs.gcp_region }}" --project ${{ inputs.shared_project_id }} &> /dev/null; then
            CONNECTOR_ID=$(gcloud compute networks vpc-access connectors describe "${{ inputs.gcp_region }}" --region "${{ inputs.gcp_region }}" --project ${{ inputs.shared_project_id }} --format="get(name)")
          else
            # fall back to selecting the most recently created connector
            CONNECTOR_ID=$(gcloud compute networks vpc-access connectors list --region="${{ inputs.gcp_region }}" --project="${{ inputs.shared_project_id }}" --sort-by="creationTimestamp desc" --format="get(CONNECTOR_ID)" | head -n 1)
          fi
          echo "VPC_CONNECTOR=${CONNECTOR_ID}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ inputs.shared_project_id }}" >> $GITHUB_ENV
        else
          # check if a connector with the region-based name exists
          if gcloud compute networks vpc-access connectors describe "${{ inputs.gcp_region }}" --region "${{ inputs.gcp_region }}" &> /dev/null; then
            CONNECTOR_ID=$(gcloud compute networks vpc-access connectors describe "${{ inputs.gcp_region }}" --region "${{ inputs.gcp_region }}" --format="get(name)")
          else
            # fall back to selecting the most recently created connector
            CONNECTOR_ID=$(gcloud compute networks vpc-access connectors list --region="${{ inputs.gcp_region }}" --sort-by="creationTimestamp desc" --format="get(CONNECTOR_ID)" | head -n 1)
          fi
          echo "VPC_CONNECTOR=${CONNECTOR_ID}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ inputs.project_id }}" >> $GITHUB_ENV
        fi
    - name: Set SQL instance
      shell: bash
      run: |
        if [ ! -z "${{ inputs.sql_instance }}" ]; then
          echo "SQL_INSTANCE_ID=--set-cloudsql-instances=${{ env.PROJECT_ID }}:asia-south2:${{ inputs.sql_instance }}" >> $GITHUB_ENV
        fi
    - id: Deploy_to_CloudRun
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ inputs.service_id }}
        image: gcr.io/${{ inputs.project_id }}/safehouse/${{ inputs.service_id }}:${{ inputs.tag }}
        secrets: ${{ inputs.secrets }}
        env_vars: ${{ inputs.env_vars }}
        region: ${{ inputs.gcp_region }}
        flags: ${{ env.SQL_INSTANCE_ID }} --port=${{ inputs.port }} --service-account ${{ inputs.service_account }} --vpc-connector=${{ env.VPC_CONNECTOR }} ${{ inputs.gcloud_args }}
